# -------------------------------------------------- #
# Note: this file originates in template-action-node #
# -------------------------------------------------- #

services:
  # ---- mega-linter ---- #
  lint:
    profiles: ["dev"]
    image: oxsecurity/megalinter-javascript:v6.15.0
    volumes:
      - ./:/tmp/lint
    environment:
      MEGALINTER_CONFIG: .github/linters/.mega-linter.yml
      REPORT_OUTPUT_FOLDER: none
      VALIDATE_ALL_CODEBASE: true

  # ---- readme generator ---- #
  readme:
    profiles: ["dev"]
    image: pandoc/minimal:2.19
    volumes:
      - ./:/data
    command: --defaults=.pandoc.yml

  app: &app
    profiles: ["app"]
    image: node:alpine
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    command: npm --no-update-notifier run start

  test:
    <<: *app
    profiles: ["test"]
    image: node:alpine
    command: npm --no-update-notifier run test -- --reporter=classic
